typography_spectrum: 0.9340939060784876
color:
  brandStrength: 0.5628613629378378
  lightness: 0.4596512382850051
  saturation: 0.4731141335796565
  rhythmicContrast: 0.3721299667377025
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.23204969055950642
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dbf118f4-71f8-412c-ab7f-0527e65c82de.png
name: Nextep Blog
navigation:
  - name: Chi siamo
    url: 'http://www.nextep.it'
    type: external
title: Stay updated
